package testsuite;

import browserfactory.BaseTest;
import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;

import java.util.Random;

public class RegisterTest extends BaseTest {
    String baseUrl = "https://demo.nopcommerce.com/";

    @Before // JUnit Annotation which will run before every method
    public void setUp() {
        openBrowser(baseUrl);
    }

    @Test // JUnit Annotation which will allow executing this method
    public void userShouldNavigateToRegisterPageSuccessfully() {
        driver.findElement(By.xpath("//a[contains(text(),'Register')]")).click();// Find Register link and click on Register link
        String expectedMessage = "Register";//Expected displayed text as per requirement
        String actualMessage = driver.findElement(By.xpath("//div[@class='header-links']/ul[1]/li[1]/a")).getText();// Find the Register text element and get the text
        Assert.assertEquals(expectedMessage, actualMessage);// Validating actual and expected message
    }

    public static String getRandomEmail() { // Method generating Random email everytime
        String chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890";
        StringBuilder random = new StringBuilder();
        Random rnd = new Random();
        while (random.length() < 10) { // length of the random string.
            int index = (int) (rnd.nextFloat() * chars.length());
            random.append(chars.charAt(index));
        }
        String email = random.toString() + "@gmail.com";
        return email;
    }

    @Test // JUnit Annotation which will allow executing this method
    public void userShouldRegisterAccountsSuccessfullySuccessfully() {
        driver.findElement(By.xpath("//a[contains(text(),'Register')]")).click();// Find Register link and click on Register link
        driver.findElement(By.id("gender-male")).click();//Select the gender radio button
        driver.findElement(By.id("FirstName")).sendKeys("Hello");//Enter the first name
        driver.findElement(By.id("LastName")).sendKeys("Patel");//Enter the Last name
        driver.findElement(By.name("DateOfBirthDay")).sendKeys("1");//Select the day
        driver.findElement(By.name("DateOfBirthMonth")).sendKeys("1");//Select the Month
        driver.findElement(By.name("DateOfBirthYear")).sendKeys("1950");//Select the Year
        driver.findElement(By.id("Email")).sendKeys(getRandomEmail());//Enter the Email address generated by getRandomEmail method
        driver.findElement(By.name("Password")).sendKeys("test1234");//Enter the Password
        driver.findElement(By.name("ConfirmPassword")).sendKeys("test1234");//Enter the Confirm Password
        driver.findElement(By.name("register-button")).click();// Click on the register Button
        String expectedMessage = "Your registration completed";//This is from the requirement
        String actualMessage = driver.findElement(By.xpath("//div[@class='result']")).getText();// Getting the actual text from element and storing in reference variable
        Assert.assertEquals("User was not able to register.",expectedMessage, actualMessage);// Validating actual and expected message
    }

    @After // JUnit Annotation which will run after every method
    public void tearDown() {
        closeBrowser();
    }
}
